langauge: ruby
sudo: required

rvm: 
  - 2.2.3
services: 
  - postgresql
  - docker
before_install:
  - sudo pip install awscli
  - aws --version
before_script:
  - psql -c 'create database ci_test_test;' -U postgres
script:
  - bundle exec rake db:reset
  - bundle exec rake
  
addons:
  postgresql: "9.4"
  
