default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ci_test_development

test:
  <<: *default
  database: ci_test_test

production:
  <<: *default
  database: ci_test_production
  username: ci_test
  password: <%= ENV['CI_TEST_DATABASE_PASSWORD'] %>
